---

- name: Update exim4.conf.template
  ansible.builtin.command:
    argv:
      - /usr/sbin/update-exim4.conf.template
      - -r
  changed_when: false
  listen: update exim4.conf.template
  become: true
  notify: update exim4.conf

- name: Update exim4.conf
  ansible.builtin.command:
    cmd: /usr/sbin/update-exim4.conf
  changed_when: false
  listen: update exim4.conf
  become: true
  notify: reload exim4

- name: Reload exim4
  ansible.builtin.service:
    name: exim4
    state: reloaded
  listen: reload exim4
  become: true

- name: Restart exim4
  ansible.builtin.service:
    name: exim4
    state: restarted
  listen: restart exim4
  become: true
